volumes:
  share: {}
  config: {}
  cache: {}

services:
  minidlna:
    build:
      context: .
      dockerfile: DlnaDockerfile
    restart: always
    network_mode: "host"
    volumes:
      - share:/share:ro
    depends_on:
      - base

  jellyfin:
    network_mode: host # Enable DLNA
    image: jellyfin/jellyfin
    privileged: true
    environment:
      - PUID=1000
      - PGID=200
      - TZ=Europe/Moscow
      - JELLYFIN_PublishedServerUrl=YOU_DOMAIN_OR_IP #optional
    volumes:
      - config:/config
      - cache:/cache
      - share:/share
      - /opt/vc/lib:/opt/vc/lib
#    ports:    # not active if host mode is activated
#      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    restart: always
    devices:
    #  RK3588 (Orange Pi 5 Max config)
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mali0:/dev/mali0
      - /dev/rga:/dev/rga
      - /dev/mpp_service:/dev/mpp_service
      - /dev/iep:/dev/iep
      - /dev/mpp-service:/dev/mpp-service
      - /dev/vpu_service:/dev/vpu_service
      - /dev/vpu-service:/dev/vpu-service
      - /dev/hevc_service:/dev/hevc_service
      - /dev/hevc-service:/dev/hevc-service
      - /dev/rkvdec:/dev/rkvdec
      - /dev/rkvenc:/dev/rkvenc
      - /dev/vepu:/dev/vepu
      - /dev/h265e:/dev/h265e
